reviews:
  auto_review:
    enabled: true
    base_branches:
      - "devel"
      - "master"
    ignore_title_keywords:
      - "l10n"
      - "localization"
      - "translation"
  from_fork:
    auto_review: true
ignore:
  - "source/Localization/**"
issues:
  enabled: true
  auto_review: false
