name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - uses: nuget/setup-nuget@v1
    - name: Restore packages in HowLongToBeat.sln
      run: nuget restore HowLongToBeat.sln

    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: msbuild HowLongToBeat.sln /t:build
